# Generated by Django 3.1.2 on 2021-04-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_goods_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goods_category',
            new_name='category',
        ),
    ]
