# Generated by Django 3.1.2 on 2021-04-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('orders', models.IntegerField()),
                ('name', models.CharField(max_length=32, verbose_name='机构或个人名称')),
                ('signature', models.CharField(blank=True, help_text='机构或个人签名', max_length=255, null=True, verbose_name='机构或个人签名')),
                ('image', models.ImageField(null=True, upload_to='teacher', verbose_name='机构或个人自选封面')),
                ('brief', models.TextField(max_length=1024, verbose_name='机构或个人描述')),
            ],
            options={
                'verbose_name': '机构或个人名称',
                'verbose_name_plural': '机构或个人名称',
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('orders', models.IntegerField()),
                ('name', models.CharField(max_length=128, verbose_name='视频名称')),
                ('video_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='video', verbose_name='封面图片')),
                ('video_type', models.SmallIntegerField(choices=[(0, '楷书'), (1, '行书'), (2, '隶书')], default=0, verbose_name='视频类型')),
                ('brief', models.TextField(blank=True, max_length=2048, null=True, verbose_name='详情介绍')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='发布日期')),
                ('attachment_path', models.FileField(blank=True, max_length=128, null=True, upload_to='attachment', verbose_name='附件路径')),
                ('students', models.IntegerField(default=0, verbose_name='观看/学习人数')),
                ('sections', models.IntegerField(default=0, verbose_name='总课时数量')),
                ('pub_sections', models.IntegerField(default=0, verbose_name='视频更新数量')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='video.organization', verbose_name='机构或个人名称')),
            ],
            options={
                'verbose_name': '视频名称',
                'verbose_name_plural': '视频名称',
                'db_table': 'video_video',
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('orders', models.IntegerField()),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='视频分类')),
            ],
            options={
                'verbose_name': '视频分类',
                'verbose_name_plural': '视频分类',
                'db_table': 'video_category',
            },
        ),
        migrations.CreateModel(
            name='VideoChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('orders', models.IntegerField()),
                ('chapter', models.SmallIntegerField(default=1, verbose_name='视频章节')),
                ('name', models.CharField(max_length=128, verbose_name='章节标题')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='章节介绍')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='发布日期')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videochapters', to='video.video', verbose_name='视频章节名称')),
            ],
            options={
                'verbose_name': '视频章节名称',
                'verbose_name_plural': '视频章节名称',
                'db_table': 'video_chapter',
            },
        ),
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('name', models.CharField(max_length=128, verbose_name='小节标题')),
                ('orders', models.PositiveSmallIntegerField(verbose_name='小节排序')),
                ('section_type', models.SmallIntegerField(choices=[(0, '文档'), (1, '视频')], default=2, verbose_name='小节种类')),
                ('section_link', models.CharField(blank=True, help_text='若是video，填vid,若是文档，填link', max_length=255, null=True, verbose_name='小节链接')),
                ('duration', models.CharField(blank=True, max_length=32, null=True, verbose_name='视频时长')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videosections', to='video.videochapter', verbose_name='视频章节')),
            ],
            options={
                'verbose_name': '小节标题',
                'verbose_name_plural': '小节标题',
                'db_table': 'video_Section',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='video_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.videocategory', verbose_name='视频分类'),
        ),
    ]
